import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../components/common/Card";
import { fetchusers } from "./api/user";
const categories = [
  "all",
  "groceries",
  "smartphones",
  "laptops",
  "fragrances",
  "skincare",
  "home-decoration",
];

export default function Home() {
  const [items, setitems] = useState([]);
  const [filter, setfilter] = useState("all");
  const [loading, setloading] = useState(true);
  const [filtered, setfiltered] = useState([]);
  const [value, setvalue] = useState("");
  let category = [];

  useEffect(() => {
    fetch("https://dummyjson.com/products/")
      .then((response) => {
        return response.json();
      })
      .catch((error) => console.log(error))
      .then((response) => {
        setitems(response.products);
      })
      .catch((error) => console.log(error));
    setloading(false);
  }, []);

  useEffect(() => {
    setvalue("");
    if (filter != "all") {
      items.map((details) => {
        if (details.category == filter) {
          category.push(details);
        }
      });
    } else {
      items.map((details) => {
        category.push(details);
      });
    }
    setfiltered(category);
  }, [filter, items]);

  useEffect(() => {
    if (value != "all") {
      items.map((details) => {
        if (details.category == value) {
          category.push(details);
        }
      });
    } else {
      items.map((details) => {
        category.push(details);
      });
    }
    setfiltered(category);
  }, [value]);

  return (
    <div>
      <Head>
        <title>Online E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <div>Loading .....</div>}
      <input
        type="text"
        value={value}
        onChange={(e) => setvalue(e.target.value)}
        placeholder="search product"
      />
      <div className="filter-wrapper">
        {categories.map((details, index) => (
          <Filter
            label={details}
            check={details == filter}
            onClick={() => setfilter(details)}
            key={index}
          />
        ))}
      </div>
      <div>
        {filtered.map((details, index) => (
          <Card
            key={index}
            description={details.description}
            imageUrl={details.thumbnail}
            title={details.title}
            price={details.price}
            brand={details.brand}
            discountPercentage={details.discountPercentage}
            stock={details.stock}
          />
        ))}
      </div>
    </div>
  );
}

function Filter({ label, check, onClick }) {
  return (
    <div className={`${"filter"} ${check ? "check" : ""}`} onClick={onClick}>
      {label}
    </div>
  );
}
